version: '3.8'
services:
  country-codle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
